SUPPORTED_LANGUAGES = {
    "odia": {
        "name": "Odia",
        "native_name": "ଓଡ଼ିଆ",
        "region": "Odisha",
        "script": "Odia script",
        "formality_levels": ["formal", "colloquial", "rural"],
        "cultural_notes": [
            "Use rice (bhaat) and farming metaphors where possible",
            "Reference Jagannath temple culture for spiritual contexts",
            "Odisha is known for handloom, tribal art (Pattachitra), and seafood",
            "Common greetings: Namaskar (ନମସ୍କାର)",
            "Avoid direct 'no' — Odia culture prefers indirect refusal",
            "Festivals: Rath Yatra, Raja Parba, Nuakhai",
        ],
        "example_idioms": {
            "very easy": "ହାତର ମଇଳା (dirt in hand — trivially easy)",
            "wasting time": "ଖଳ ଖଳ ଚାଲ (walking in mud — going nowhere)",
            "act fast": "ଲୁହ ଶୁଖିବା ଆଗରୁ (before tears dry)",
        },
    },
    "tamil": {
        "name": "Tamil",
        "native_name": "தமிழ்",
        "region": "Tamil Nadu / Sri Lanka",
        "script": "Tamil script",
        "formality_levels": ["formal", "colloquial", "Chennai slang"],
        "cultural_notes": [
            "Tamil has classical literature — treat language with reverence",
            "Rice, sambar, filter coffee are cultural anchors",
            "Reference Pongal, Karthigai Deepam festivals for seasonal context",
            "Cinema (Kollywood) references resonate deeply with youth",
            "Respect elders explicitly — use 'neenga' not 'nee' for respect",
            "Regional pride: Tamil is one of world's oldest living languages",
        ],
        "example_idioms": {
            "very easy": "கை மண் அளவு (handful of soil — effortless)",
            "wasting time": "காலத்தை கடத்துவது (letting time drift away)",
            "act fast": "வேகமாக நட (walk briskly)",
        },
    },
    "bengali": {
        "name": "Bengali",
        "native_name": "বাংলা",
        "region": "West Bengal / Bangladesh",
        "script": "Bengali script",
        "formality_levels": ["formal", "colloquial", "Kolkata street"],
        "cultural_notes": [
            "Literature and Rabindranath Tagore are deep cultural touchstones",
            "Fish (maach) and mustard oil are central to culinary identity",
            "Durga Puja is the biggest festival — community and celebration",
            "Kolkata coffee house culture: intellectual, argumentative, warm",
            "Music (Rabindra Sangeet, Baul) references add emotional depth",
            "Bengalis express emotion strongly — understatement is unusual",
        ],
        "example_idioms": {
            "very easy": "জলের মতো সহজ (easy as water)",
            "wasting time": "সময় নষ্ট করা (spoiling time)",
            "act fast": "তাড়াতাড়ি করো (do it quickly)",
        },
    },
    "hindi": {
        "name": "Hindi",
        "native_name": "हिन्दी",
        "region": "North India (with regional dialects)",
        "script": "Devanagari",
        "formality_levels": ["formal", "colloquial", "Hinglish"],
        "cultural_notes": [
            "Bollywood references are universally understood",
            "Cricket metaphors work extremely well",
            "Chai culture — use tea as metaphor for comfort and discussion",
            "Family structure is central — reference 'ghar' (home) and elders",
            "Holi, Diwali, Eid all celebrated — be inclusive",
            "Code-switching to English (Hinglish) is natural for youth",
        ],
        "example_idioms": {
            "very easy": "बाएँ हाथ का खेल (left hand's game — child's play)",
            "wasting time": "वक़्त बर्बाद करना (wasting precious time)",
            "act fast": "जल्दी करो (hurry up)",
        },
    },
    "telugu": {
        "name": "Telugu",
        "native_name": "తెలుగు",
        "region": "Andhra Pradesh / Telangana",
        "script": "Telugu script",
        "formality_levels": ["formal", "colloquial", "Hyderabad Dakhni"],
        "cultural_notes": [
            "Telugu cinema (Tollywood) has huge cultural influence",
            "Biryani (Hyderabadi) is a cultural icon — use food metaphors",
            "Ugadi and Sankranti are major festivals",
            "Strong sense of regional identity between Andhra and Telangana",
            "Technology hub — Hyderabad references resonate with youth",
            "Hospitality is paramount — guests are treated like gods (Atithi Devo Bhava)",
        ],
        "example_idioms": {
            "very easy": "చేతి వేళ్ళతో లెక్కపెట్టవచ్చు (count on your fingers)",
            "wasting time": "సమయం వృధా చేయడం (wasting God-given time)",
            "act fast": "త్వరగా చేయి (do it swiftly)",
        },
    },
}

FORMALITY_DESCRIPTIONS = {
    "formal": "Use formal grammar, complete sentences, respectful address. Suitable for professional emails, academic writing, official communication.",
    "colloquial": "Natural everyday speech. Contractions allowed, some regional slang. Like talking to a friend your age.",
    "rural": "Traditional dialect with older vocabulary, proverbs, and agricultural metaphors. Suitable for elder-facing communication.",
    "Chennai slang": "Fast-paced urban Tamil with Kollywood references and youth slang. Like texting a college friend.",
    "Kolkata street": "Warm, slightly argumentative, rich with cultural references. Classic adda (chat) style.",
    "Hinglish": "Natural English-Hindi mix. How urban North Indian youth actually speak and text.",
    "Hyderabad Dakhni": "Hyderabadi Urdu-Telugu blend. Warm, humorous, with Nawabi cultural flavour.",
}
